name: artifacts.yaml
on:
  push:
    branches: [ main ]
  pull_request:

env:
  VCPKG_BUILD_TYPE: release
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/cpp/vcpkg/scripts/buildsystems/vcpkg.cmake
  VCPKG_BINARY_SOURCES: files,${{ github.workspace }}/vcpkg_cache,readwrite

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl make cmake nasm gcc libssl-dev nlohmann-json3-dev doctest-dev

      - uses: ./.github/actions/vcpkg-setup
        with:
          runner: linux
          crypto: boringssl
          cache-dir: vcpkg_cache

      - name: Setup build directory
        working-directory: cpp
        run: |
          cmake -Bbuild \
            -DVCPKG_MANIFEST_DIR=vcpkg-alts/boringssl \
            -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DBUILD_SHARED_LIBS=ON \
            -DREQUIRE_BORINGSSL=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DVCPKG_TARGET_ARCHITECTURE=x86_64 \
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=${{ github.workspace }}/cpp/build/Release \
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=${{ github.workspace }}/cpp/build/Release

      - name: Build Artifacts
        working-directory: cpp
        run: |
          cmake --build build --config Release --target libdave

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: Linux-x86_64
          path: cpp/build/Release/libdave.so

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ./.github/actions/vcpkg-setup
        with:
          runner: windows
          crypto: boringssl
          cache-dir: vcpkg_cache

      - name: Setup build directory
        shell: cmd
        working-directory: cpp
        run: |
          cmake -Bbuild ^
            -DVCPKG_MANIFEST_DIR=vcpkg-alts/boringssl ^
            -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake ^
            -DBUILD_SHARED_LIBS=ON ^
            -DREQUIRE_BORINGSSL=ON ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DVCPKG_TARGET_ARCHITECTURE=x86_64 ^
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=${{ github.workspace }}/cpp/build/Release ^
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=${{ github.workspace }}/cpp/build/Release ^
            -DVCPKG_TARGET_TRIPLET=x64-windows-static-md

      - name: Build Artifacts
        working-directory: cpp
        run: |
          cmake --build build --config Release --target libdave

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: Windows-x86_64
          path: cpp/build/Release/dave.dll

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        shell: bash
        run: brew install nasm go

      - uses: ./.github/actions/vcpkg-setup
        with:
          runner: darwin-${{ matrix.arch }}
          crypto: boringssl
          cache-dir: vcpkg_cache

      - name: Setup build directory
        working-directory: cpp
        run: |
          cmake -Bbuild \
            -DVCPKG_MANIFEST_DIR=vcpkg-alts/boringssl \
            -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DBUILD_SHARED_LIBS=ON \
            -DREQUIRE_BORINGSSL=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DVCPKG_TARGET_ARCHITECTURE=${{ matrix.arch }} \
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=${{ github.workspace }}/cpp/build/Release \
            -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=${{ github.workspace }}/cpp/build/Release

      - name: Build Artifacts
        working-directory: cpp
        run: |
          cmake --build build --config Release --target libdave

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: Darwin_${{ matrix.arch }}
          path: cpp/build/Release/libdave.dylib
